# Generated by Django 4.2.18 on 2025-01-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_bookmark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
