# Generated by Django 4.2.18 on 2025-01-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_comment_delete_postview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='text',
        ),
    ]
