# Generated by Django 4.2.18 on 2025-01-30 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_rename_created_at_comment_created_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
